#端口
server:
  port: 8080
#服务名
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启后无需每个服务单独配置
          enabled: true
          lower-case-service-id: true
      routes: #路由配置:参数为一个List
          - id: web #唯一标识
            uri: lb://web #转发的地址,写服务名称
            predicates:
              - Path=/web/** #判断匹配条件,即地址带有/web/**的请求,会转发至lb:web
            filters:
              - StripPrefix=1 #去掉Path前缀,参数为1代表去掉/web
              - name: Hystrix
                args:
                  name: default
                  fallbackUri: 'forward:/default-fallback'
          - id: admin
            uri: lb://admin
            predicates:
              - Path=/admin/**
            filters:
              - StripPrefix=1
              - name: Hystrix
                  args:
                    name: default
                    fallbackUri: 'forward:/default-fallback'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8081/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
