spring:
  #RabbitMq
  rabbitmq:
    host: 123.206.217.166
    port: 5672
    username: guest
    password: Ljy123456789
  redis:
    host: 123.206.217.166
    port: 6379
    timeout: 1000
  #mail
  mail:
    username: lijiayu@ljygrgc.onexmail.com
    password: Ljy123456789
    host: smtp.exmail.qq.com

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true