spring:
  #RabbitMq
  rabbitmq:
    host: 123.206.217.166
    port: 5672
    username: guest
    password: Ljy123456789
  redis:
    host: 47.111.250.3
    port: 6379
    timeout: 1000
  #mail
  mail:
    username: turtle_blog@163.com
    password: turtle123456
    host: smtp.163.com

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true