spring:
  datasource:
    druid:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 主数据源，默认的
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://rm-bp1j580ksg6bnh2h1mo.mysql.rds.aliyuncs.com:3306/tblog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: tblog
        password: Tblog6888@
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://rm-bp1j580ksg6bnh2h1mo.mysql.rds.aliyuncs.com:3306/tblog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: tblog
        password: Tblog6888@
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 25
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,logback
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    #RabbitMq
  rabbitmq:
    host: 123.206.217.166
    port: 5672
    username: guest
    password: Ljy123456789
    ## Redis 配置
  redis:
    host: 47.111.250.3
    port: 6379
    timeout: 1000
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
seata:
  enabled: true
  applicationId: ${spring.application.name}
  txServiceGroup: tblog-service-group
  service:
    vgroup-mapping:
      tblog-service-group: seata-server
  registry:
    type: eureka
    eureka:
      serviceUrl: http://47.111.250.3:8081/eureka
      application: seata-server
#web请求日志
logbook:
  format:
    style: curl

#日志级别
logging:
  level:
    root: info
    org.zalando.logbook: TRACE
    com.turtle: TRACE
server:
  port: 8089
  servlet:
    context-path: /v1

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://47.111.250.3:8081/eureka/
  instance:
    #    ip-address: 121.43.184.44
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
##jwt
tokenHead: bearer
tokenHeader: Authorization
rememberMeExpiresSecond: 259200
audience:
  clientId: 31caa0168d3d456ca0f6b05952122fdb
  base64Secret: MzFjYWEwMTY4ZDNkNDU2Y2EwZjZiMDU5NTIxMjJmZGI=
  name: turtle
  expiresSecond: 3600

# 是否启用httpclient
feign:
  httpclient:
    enabled: false
  # 请求连接超时时间（毫秒）
  #    connection-timeout: 200
  # 是否启用httpok（性能比httpclient高）
  okhttp:
    enabled: true
  sentinel:
    enabled: false
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        # 每台服务器最多重试次数，但是首次调用不包括在内
        MaxAutoRetries: 1
        # 最多重试多少台服务器
        MaxAutoRetriesNextServer: 1
        # 无论是请求超时或者socket read timeout都进行重试
        OkToRetryOnAllOperations: false
    #admin:
    #  ribbon:
    #负载策略   RandomRule：随机     RoundRobinRule：轮询
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# hystrix熔断时间
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 6000
swagger:
  enable: true

#顶象
appHeader: CodeToken
appId: f779bcf183706417df081bbaa920d435
appSecret: 2251cf3f011339a43fb81cc7192ec498

#腾讯位置服务
addressKey: 4IGBZ-EM5L6-PPFS7-MSM2G-4BAA7-QWBMJ
